#!/usr/bin/bash
#This code is generated by PipelineDog.

cuffdiff -o /mnt/working/cuffidff -L ,undefined,undefined,undefined --multi-read-correct -p 16 --verbose --dispersion-method bind /mnt/input/statics/mm9/mm9_genes_archive_2014.gtf .,undefined,undefined   undefined,undefined undefined&
wait