#!/usr/bin/bash
#This code is generated by PipelineDog.

cuffdiff -o /mnt/working/cuffidff -L ControlCr,Cdx2koCr,BrafHetCr,Cdx2BrafCr,SmadBrafCr --multi-read-correct -p 16 --verbose --dispersion-method bind /mnt/input/statics/mm9/mm9_genes_archive_2014.gtf /home/cuffquant/ControlCr.rep1.cxb,/home/cuffquant/ControlCr.rep2.cxb,/home/cuffquant/ControlCr.rep3.cxb /home/cuffquant/Cdx2koCr.rep1.cxb,/home/cuffquant/Cdx2koCr.rep2.cxb /home/cuffquant/BrafHetCr.rep1.cxb,/home/cuffquant/BrafHetCr.rep2.cxb /home/cuffquant/Cdx2BrafCr.rep1.cxb,/home/cuffquant/Cdx2BrafCr.rep2.cxb /home/cuffquant/SmadBrafCr.rep1.cxb&
wait
cuffdiff -o /mnt/working/cuffidff -L ControlCr,Cdx2koCr,BrafHetCr,Cdx2BrafCr,SmadBrafCr --multi-read-correct -p 16 --verbose --dispersion-method bind /mnt/input/statics/mm9/mm9_genes_archive_2014.gtf /home/cuffquant/ControlCr.rep1.cxb,/home/cuffquant/ControlCr.rep2.cxb,/home/cuffquant/ControlCr.rep3.cxb /home/cuffquant/Cdx2koCr.rep1.cxb,/home/cuffquant/Cdx2koCr.rep2.cxb /home/cuffquant/BrafHetCr.rep1.cxb,/home/cuffquant/BrafHetCr.rep2.cxb /home/cuffquant/Cdx2BrafCr.rep1.cxb,/home/cuffquant/Cdx2BrafCr.rep2.cxb /home/cuffquant/SmadBrafCr.rep1.cxb&
wait