#!/usr/bin/bash
#This code is generated by PipelineDog.

samtools view -h /home/usr/file1.bam /home/usr/file1.sam&
samtools view -h /home/usr/file2.bam /home/usr/file2.sam&
samtools view -h /home/usr/file3.bam /home/usr/file3.sam&
wait