#!/usr/bin/bash
#This code is generated by PipelineDog.
cd /Users/zhouanbo/ElectronProjects/pipelinedog/examples/fastqc2cufflinks

fastqc -o fastqc/f1 /home/f1.fastq&
fastqc -o fastqc/f2 /home/f2.fastq&
fastqc -o fastqc/f3 /home/f3.fastq&
fastqc -o fastqc/f4 /home/f4.fastq&
fastqc -o fastqc/f5 /home/f5.fastq&
wait

tophat2 --output-dir tophat2/f1 --num-threads 16 /mnt/input/ref/Mus_musculus/UCSC/mm9/Sequence/Bowtie2Index/genome /home/f1.fastq &> tophat2/f1.log&
tophat2 --output-dir tophat2/f2 --num-threads 16 /mnt/input/ref/Mus_musculus/UCSC/mm9/Sequence/Bowtie2Index/genome /home/f2.fastq &> tophat2/f2.log&
tophat2 --output-dir tophat2/f3 --num-threads 16 /mnt/input/ref/Mus_musculus/UCSC/mm9/Sequence/Bowtie2Index/genome /home/f3.fastq &> tophat2/f3.log&
tophat2 --output-dir tophat2/f4 --num-threads 16 /mnt/input/ref/Mus_musculus/UCSC/mm9/Sequence/Bowtie2Index/genome /home/f4.fastq &> tophat2/f4.log&
tophat2 --output-dir tophat2/f5 --num-threads 16 /mnt/input/ref/Mus_musculus/UCSC/mm9/Sequence/Bowtie2Index/genome /home/f5.fastq &> tophat2/f5.log&
wait

cufflinks --output-dir cufflinks/f1 --num-threads 16 --GTF /mnt/input/statics/mm9/mm9_genes_archive_2014.gtf --frag-bias-correct /mnt/input/ref/Mus_musculus/UCSC/mm9/Sequence/WholeGenomeFasta/genome.fa --multi-read-correct --upper-quartile-norm tophat2/f1/accepted_hits.bam&
cufflinks --output-dir cufflinks/f2 --num-threads 16 --GTF /mnt/input/statics/mm9/mm9_genes_archive_2014.gtf --frag-bias-correct /mnt/input/ref/Mus_musculus/UCSC/mm9/Sequence/WholeGenomeFasta/genome.fa --multi-read-correct --upper-quartile-norm tophat2/f2/accepted_hits.bam&
cufflinks --output-dir cufflinks/f3 --num-threads 16 --GTF /mnt/input/statics/mm9/mm9_genes_archive_2014.gtf --frag-bias-correct /mnt/input/ref/Mus_musculus/UCSC/mm9/Sequence/WholeGenomeFasta/genome.fa --multi-read-correct --upper-quartile-norm tophat2/f3/accepted_hits.bam&
cufflinks --output-dir cufflinks/f4 --num-threads 16 --GTF /mnt/input/statics/mm9/mm9_genes_archive_2014.gtf --frag-bias-correct /mnt/input/ref/Mus_musculus/UCSC/mm9/Sequence/WholeGenomeFasta/genome.fa --multi-read-correct --upper-quartile-norm tophat2/f4/accepted_hits.bam&
cufflinks --output-dir cufflinks/f5 --num-threads 16 --GTF /mnt/input/statics/mm9/mm9_genes_archive_2014.gtf --frag-bias-correct /mnt/input/ref/Mus_musculus/UCSC/mm9/Sequence/WholeGenomeFasta/genome.fa --multi-read-correct --upper-quartile-norm tophat2/f5/accepted_hits.bam&
wait
